T14014
endlessm/emeus pull request #1
Opened 2016-11-24 14:52 UTC by tchx84

https://phabricator.endlessm.com/T14014

2016-11-28 22:21 UTC, ptomato requested changes
Some minor comments, also questions that I'm not sure about.

Just FYI, we decided to avoid separate debian branches on new repositories if possible, but in this case it's not possible since we're not the upstream.

2016-11-28 22:21 UTC, ptomato commented on debian/rules
> +	--prefix=${DEB_PREFIX} \
Isn't all this done automatically?

2016-11-28 22:21 UTC, ptomato commented on debian/source/format
> +3.0 (native)
Should be `quilt`, I believe, `native` is only for tools written by Debian themselves

2016-11-28 22:21 UTC, ptomato commented on debian/control
> +Depends: ${misc:Depends},
Needs `${gir:Depends}` here as well

2016-11-28 22:21 UTC, ptomato commented on debian/control
> +               meson,
`meson (>= 0.36)`?

2016-11-28 22:21 UTC, ptomato commented on debian/control
> +Build-Depends: autotools-dev,
What does `autotools-dev` provide here?

2016-11-29 15:15 UTC, tchx84 commented on debian/rules
> +	--prefix=${DEB_PREFIX} \
I found two issues which I haven't found other ways to solve: a) make it use multi-arch path for libdir and b) dh_auto_configure receives paths without substitution:

```
./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libexecdir=\${prefix}/lib/emeus --disable-maintainer-mode --disable-dependency-tracking
```

I don't know really if we give special treatment to those in our configure file.

2016-11-29 19:09 UTC, tchx84 commented
@ptomato pushed the changes, but as we talked, I left the params in the rules so we don't need to make that configure script a real configure file.

2016-11-29 20:11 UTC, ptomato approved these changes

2016-11-29 20:11 UTC, merged